#!/bin/sh
#
# ProFTPD disabled
#

case "$1" in
  start|stop|restart|reload)
    # Do nothing
    echo "ProFTPD is disabled. Delete this file from overlay to enable it."
    exit 0
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}"
    exit 1
esac
