#!/bin/sh
### BEGIN INIT INFO
# Provides:          usbip-autobinder
# Required-Start:    $remote_fs $network usbipd
# Required-Stop:     $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Auto-bind USB devices to usbip-host
# Description:       Periodically runs usbip-autobinder.sh to bind devices
### END INIT INFO

NAME=usbip-autobinder
DAEMON=/opt/beamer/usbip-autobinder.sh
CHDIR=/opt/beamer
PIDFILE=/var/run/$NAME.pid
DESC="USB/IP auto binder"
LOG_TAG="S91usbip-autobinder"

test -x $DAEMON || exit 0

# Common Beamer init helpers (provides log_daemon_msg/log_end_msg/log_failure_msg)
[ -r /etc/init.d/common-func ] && . /etc/init.d/common-func

case "$1" in
  start)
    log_daemon_msg "Starting $DESC" "$NAME"
    # Clean up stale pidfile if process not running
    if [ -f "$PIDFILE" ]; then
      oldpid=`cat "$PIDFILE" 2>/dev/null`
      if [ -n "$oldpid" ] && kill -0 "$oldpid" 2>/dev/null; then
        log_failure_msg "$NAME already running (pid $oldpid)"
        log_end_msg 0
        exit 0
      else
        rm -f "$PIDFILE"
      fi
    fi
    start-stop-daemon --start --quiet --chdir $CHDIR --pidfile $PIDFILE --make-pidfile --background --exec $DAEMON
    status=$?
    log_end_msg $status
    ;;
  stop)
    log_daemon_msg "Stopping $DESC" "$NAME"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --retry 5
    status=$?
    # Ensure stale pidfile is removed if process is no longer running
    if [ -f "$PIDFILE" ]; then
      pid=`cat "$PIDFILE" 2>/dev/null`
      if [ -z "$pid" ] || ! kill -0 "$pid" 2>/dev/null; then
        rm -f "$PIDFILE"
      fi
    fi
    log_end_msg $status
    ;;
  restart|force-reload)
    $0 stop
    $0 start
    ;;
  status)
    if [ -f "$PIDFILE" ]; then
      pid=`cat "$PIDFILE" 2>/dev/null`
      if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
        echo "$NAME is running (pid $pid)"
        exit 0
      else
        echo "$NAME is not running, but pidfile exists"
        exit 1
      fi
    else
      echo "$NAME is not running"
      exit 3
    fi
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
